using System.Collections.Generic;
using System.Linq;
using DWSIM.Interfaces;
using DWSIM.Interfaces.Enums;

namespace DWSIM.Extensions.ReactionFinder.Logic
{
    /// <summary>
    /// Orchestrates all individual suggesters, merges their output, and
    /// de-duplicates on the stoichiometric signature. The caller is the
    /// ReactionFinderControl (UI).
    /// </summary>
    public static class ReactionSuggester
    {
        public static List<SuggestedReaction> SuggestAll(IFlowsheet flowsheet)
        {
            var compounds = flowsheet?.SelectedCompounds?.Values
                ?.Select(c => c as ICompoundConstantProperties)
                .Where(c => c != null)
                .ToList() ?? new List<ICompoundConstantProperties>();

            var idx = new CompoundIndex(compounds);

            var all = new List<SuggestedReaction>();
            all.AddRange(CombustionSuggester.Suggest(idx));
            all.AddRange(KineticSuggester.Suggest(idx));
            all.AddRange(CatalyticSuggester.Suggest(idx));
            all.AddRange(AcidBaseSuggester.Suggest(idx));
            all.AddRange(PrecipitationSuggester.Suggest(idx));
            all.AddRange(ElectrolyteDissociationSuggester.Suggest(idx));
            all.AddRange(LibrarySuggester.Suggest(idx));

            // De-dupe on stoichiometry (ignoring the category prefix) so the
            // same reaction isn't shown twice across suggesters.
            var seen = new HashSet<string>();
            var unique = new List<SuggestedReaction>();
            foreach (var s in all)
            {
                var key = string.IsNullOrEmpty(s.Signature) ? System.Guid.NewGuid().ToString() : s.Signature;
                var core = key.Contains(":") ? key.Substring(key.IndexOf(':') + 1) : key;
                if (!seen.Add(core)) continue;
                unique.Add(s);
            }

            // For every non-Equilibrium suggestion, emit an additional
            // Equilibrium variant whose K is computed from the Gibbs free
            // energy of reaction. Phase is inferred from the physical state
            // of each participating compound at normal conditions.
            var variants = new List<SuggestedReaction>();
            foreach (var s in unique)
            {
                if (s.Reaction == null) continue;
                if (s.Reaction.ReactionType == ReactionType.Equilibrium) continue;

                var stoich = s.Reaction.Components
                    .ToDictionary(kv => kv.Key, kv => kv.Value.StoichCoeff);
                var participating = stoich.Keys
                    .Select(idx.FindByName)
                    .Where(cp => cp != null)
                    .ToList();
                var phase = ReactionFactory.InferPhase(participating);

                var baseName = string.IsNullOrEmpty(s.Reaction.Name)
                    ? s.DisplayName : s.Reaction.Name;
                var eqRxn = ReactionFactory.BuildEquilibrium(
                    baseName + " (Gibbs Eq.)",
                    "Equilibrium variant auto-generated by Reaction Finder. " +
                    "K is computed from the Gibbs free energy of reaction. " +
                    "Phase inferred from compound states at normal conditions.",
                    stoich,
                    phase);
                eqRxn.Equation = ReactionFactory.BuildEquationString(eqRxn, idx.FormulaOf);

                variants.Add(new SuggestedReaction
                {
                    Category = s.Category,
                    DisplayName = baseName + "  (Gibbs-Eq, " + phase + ")",
                    Equation = eqRxn.Equation,
                    Reaction = eqRxn,
                    // Distinct signature so it survives future dedup passes.
                    Signature = "eq-gibbs:" + ReactionFactory.Signature(stoich)
                });
            }
            unique.AddRange(variants);
            return unique;
        }
    }
}
